server:
  port: 8888

#person:
#  user: user
#  password: 123
#  age: 44
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 125521
    url: jdbc:mysql://127.0.0.1:3306/test1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kano.domain
